### ISSUE TITLE
Question: where are Exceptions gone in extra threads?

### ISSUE THREAD

**Issue by wsw70** [custom-components/pyscript#110]
I need to call an API in one of my scripts. The documentation discusses this and suggests `task.executor()`. It does not seem to manage exceptions, though. 

Consider the code below, which does not use threading and works correctly (but this is not the right thing to do for I/O tasks):

```
class MyEx(Exception):
    pass

def raise_ex():
    log.info("in raise function")
    try:
        raise MyEx()
    except MyEx:
        log.warning("caught MyEx")

def raise_ex2():
    raise MyEx()

@service
def testing_raise(**data):
    raise_ex()
    raise_ex2()
```

Calling the service `pyscript.testing_raise` gives

```
2020-12-04 16:17:25 DEBUG (MainThread) [custom_components.pyscript.eval] file.dash__meteo.testing_raise: calling raise_ex(, {})
2020-12-04 16:17:25 DEBUG (MainThread) [custom_components.pyscript.eval] file.dash__meteo.testing_raise: calling info("in raise function", {})
2020-12-04 16:17:25 INFO (MainThread) [custom_components.pyscript.file.dash__meteo.testing_raise] in raise function
2020-12-04 16:17:25 DEBUG (MainThread) [custom_components.pyscript.eval] file.dash__meteo.testing_raise: calling MyEx(, {})
2020-12-04 16:17:25 DEBUG (MainThread) [custom_components.pyscript.eval] file.dash__meteo.testing_raise: calling warning("caught MyEx", {})
2020-12-04 16:17:25 WARNING (MainThread) [custom_components.pyscript.file.dash__meteo.testing_raise] caught MyEx
2020-12-04 16:17:25 DEBUG (MainThread) [custom_components.pyscript.eval] file.dash__meteo.testing_raise: calling raise_ex2(, {})
2020-12-04 16:17:25 DEBUG (MainThread) [custom_components.pyscript.eval] file.dash__meteo.testing_raise: calling MyEx(, {})
2020-12-04 16:17:25 ERROR (MainThread) [custom_components.pyscript.file.dash__meteo.testing_raise] Exception in <file.dash__meteo.testing_raise> line 39:
        raise MyEx()
              ^
MyEx:
```

This is fone, the exception is caught once and then thrown out.

Now the version with `task.executor` and standard threading:

```
class MyEx(Exception):
    pass

def raise_ex():
    log.info("in raise function")
    try:
        raise MyEx()
    except MyEx:
        log.warning("caught MyEx")

def raise_ex2():
    raise MyEx()

@service
def testing_raise(**data):
    task.executor(raise_ex)
    task.executor(raise_ex2)
    threading.Thread(target=raise_ex).start()
    threading.Thread(target=raise_ex2).start()
```

It outputs:

```
2020-12-04 16:25:21 DEBUG (MainThread) [custom_components.pyscript.eval] file.dash__meteo.testing_raise: calling executor(<custom_components.pyscript.eval.EvalFuncVarAstCtx object at 0x7fe8ec485c10>, {})
2020-12-04 16:25:21 DEBUG (MainThread) [custom_components.pyscript.eval] file.dash__meteo.testing_raise: calling executor(<custom_components.pyscript.eval.EvalFuncVarAstCtx object at 0x7fe8ec485d90>, {})
2020-12-04 16:25:21 DEBUG (MainThread) [custom_components.pyscript.eval] file.dash__meteo.testing_raise: calling Thread(, {'target': <custom_components.pyscript.eval.EvalFuncVarAstCtx object at 0x7fe8ec4855e0>})
2020-12-04 16:25:21 DEBUG (MainThread) [custom_components.pyscript.eval] file.dash__meteo.testing_raise: calling start(, {})
2020-12-04 16:25:21 DEBUG (MainThread) [custom_components.pyscript.eval] file.dash__meteo.testing_raise: calling Thread(, {'target': <custom_components.pyscript.eval.EvalFuncVarAstCtx object at 0x7fe8ec485af0>})
2020-12-04 16:25:21 DEBUG (MainThread) [custom_components.pyscript.eval] file.dash__meteo.testing_raise: calling start(, {})
```

Nothing about the exceptions (caught or not).

This is a bit problematic with calls such as `requests` (that are in the documentation) because it is not known whether they succeed or not.

**Comment by dlashua** [comment]
You've run into some of the less used pieces of pyscript. So, congrats. :)

If you look at what is being returned by `task.executor` you'll see that it is a coroutine. This is the root of the problem. The exception is never raised because the method you expect to have run (`raise_ex`) is never actually run.

In pyscript, even though `def raise_ex():` doesn't look like you're making a coroutine (async function) you actually are, through a few hoops. Every method you define ends up being a "class" internally to pyscript. And this particular class is callable and, when called, returns a coroutine. So, task.executor "calls" that class, gets the returned coroutine, and returns it to you, but never runs it. 

The short solution to all of this is, if you need to run functions in the executor, then those functions have to exist WITHOUT all the features pyscript brings. They have to be pure python with no access to log.*, state.*, service.call, etc. It's almost as though it's not even connected to Home Assistant. And, to write such functions, you have to take a few extra steps.

They are outline [in the docs](https://hacs-pyscript.readthedocs.io/en/stable/reference.html#importing). You can jump down to the paragraph that starts with "So if you plan to run large chunks of code in pyscript".

If you would like to use pyscript functionality (like service.call, for instance) and do I/O and use the task.executor() then you need to break the job up into pieces that don't do I/O and use pyscript, and pieces that do I/O and don't use pyscript.

In most cases, the easiest solution is to do what you want to do with an async capable library or code. But, if that isn't possible, these are the tools available.

Pyscript does this to make it EASIER on the end user. But, when doing more advanced things, ultimately, it makes it little be harder. It makes it easier by not requiring the end user to know what async is, or when to await, or any of that business when writing MOST automations. But, in your case, you need specific control over async, and await, and all of that in order to properly hand data from the async event loop, into the executor, and back again.

**Comment by dlashua** [comment]
Speaking specifically to using `requests`, the docs mention this as the "better" method (in a "bad", "better", "best") scale:

```
import requests

url = "https://raw.githubusercontent.com/custom-components/pyscript/master/README.md"
resp = task.executor(requests.get, url)
```

This works fine because `requests.get` is provided by a separate module. Because that module exists OUTSIDE of pyscript, it's a real module with real functions instead of having the "everything gets turned into a class" treatment that a method you write inside of pyscript gets. 

An example of where this can get you is like this. The below code is wrong:

```
import requests

def does_google_say_google():
  res =requests.get('http://google.com')
  if "google" in res.text:
    return True
  return False

@time_trigger('startup')
def dothething():
  result = task.executor(does_google_say_google)
  if result:
    log.info('google says google')
```

The reason this doesn't work is because of where the "task.executor" is issued. Use it at the closest possible point of task execution, like so:

```
import requests

def does_google_say_google():
  res = task.executor(requests.get,'http://google.com')
  if "google" in res.text:
    return True
  return False

@time_trigger('startup')
def dothething():
  result = does_google_say_google()
  if result:
    log.info('google says google')
```

**Comment by craigbarratt** [comment]
Sorry, I've been busy working on rewriting `reload`.

One important point is that threading most definitely doesn't work with pyscript.  Pyscript is not thread safe, and many of the HASS primitives it calls aren't thread safe either (ie, they need to run in the main event loop).

**Comment by wsw70** [comment]
**Thank you very much for the detailed explanations.**

I am not a developer but casually use Python for 10 years and having always had used threading, I see it is time to move to more modern solutions.

I, for now, wanted to try the subfolder solution outlined in the docs @dlashua pointed to (to separate the non-pyscript code), but I have a hard time having it recognized in imports.

My folders structure is the following:

```
/etc/docker/data/hass/pyscript # tree  
.
├── automation__fuite_eau.py
├── automation__lights.py
├── automation__volets.py
├── automation__zigbee_rf433.py
├── dash
│   ├── dash__darkmode.py
│   ├── __init__.py
│   └── meteo.py
├── dash__darkmode.py
├── dash.py
├── requirements.txt
└── test1.py
```

The `dash` directory will have all kinds of microservices that power a homemade dashboard (something independent of HA, written in JS). They used to be in different places (running in their own docker containers, then in one big, then in AppDaemon but I feel that their best place will be in `pyscript` as they may set some information useful to HA through MQTT (so no HA/pyscript specific calls are needed there, the code is standalone).

`dash.py` is expected to trigger these microservices, via `pyscript` mechanisms (usually time or mqtt based). I imagined it to be something like:

```
/etc/docker/data/hass/pyscript # cat dash.py   

import sys
if "config/dash" not in sys.path:
    sys.path.append("config/dash")

from dash.meteo import meteo

@service
def run_meteo(**data):
    meteo()
```

I tried all possible combinations of the first part `if ...` (with `config` and without - not sure why it was there in the docs), and of the import `from dash.meteo import meteo`  (this one makes the most sense to me as I am importing the function `meteo()` from the module `meteo.py` located in `dash` - but I tried also others just in case.)

I always end up with an import error such as 

```
2020-12-06 14:11:43 ERROR (MainThread) [custom_components.pyscript.file.dash] Exception in </config/pyscript/dash.py> line 5:
    from dash.meteo import meteo
    ^
ModuleNotFoundError: No module named 'dash'
```

The `meteo.py` module itself is below for completeness (it is a draft and won't work as it - but the problem for now is that I am not even able to import it)

```
/etc/docker/data/hass/pyscript # cat dash/meteo.py 

import requests
import json
import logging as log
import paho.mqtt.publish

def meteo():
    try:
        r = requests.get(
            "https://api.darksky.net/forecast/b...1?lang=fr&units=si",
            timeout=10
        )
        r.raise_for_status()
    except Exception as e:
        log.warning(f"cannot connect to weather API: {e}")
    else:
        log.debug(r.json())
        paho.mqtt.publish.single(
            topic=f"dehors/meteo",
            payload=json.dumps(r.json()),
            retain=True,
            hostname="mqtt.myserver"
        )
```

**Comment by dlashua** [comment]
I think the import solution is not working for you because of a paths issue.

'config/' as mentioned in the docs is your Home Assistant config directory. So your tree should look something like this:

```
config/
  configuration.yaml
  pyscript/
    somescript.py
  pyscript_modules/
    somemodule.py
```

With this in place, your import would look like this:

```
import sys
if "config/pyscript_modules" not in sys.path:
    sys.path.append("config/pyscript_modules")
```

Take note that the `pyscript_modules` directory is NOT under `pyscript`.
