### ISSUE TITLE
state_active not always working as expected

### ISSUE THREAD

**Issue by dlashua** [custom-components/pyscript#113]
```
@state_trigger('camera.sofie.vacuum_position')
@state_active("camera.sofie.vacuum_position.x != pyscript.sofie_location.x or camera.sofie.vacuum_position.y != pyscript.sofie_location.y")
def sofie_location():
    if not eval("camera.sofie.vacuum_position.x != pyscript.sofie_location.x or camera.sofie.vacuum_position.y != pyscript.sofie_location.y"):
        log.info('no change')
        return
```

Despite the `eval`ed string and `@state_active` string being the same, I see "no change" logged very often.

I'm not sure if it matters (since the `eval`ed line is catching it so it must "work") but `vacuum_postition` is an object type specific to the integration I'm using (which I didn't expect and haven't seen before). 'x' and 'y' are both attributes of that object that have `int` values.

Also worth noting, @state_trigger still triggers this method even though the values haven't changed because it compares the `vacuum_position` object in the old and new state and, while the values haven't changed, the integration, apparently, generates a new object with every update, so the `id()` is different, hence, they compare as not equal.

**Comment by craigbarratt** [comment]
The most likely explanation is this is a race condition.  The `@state_trigger` and `@state_active` expressions are evaluated based on the state value in the state changed event, which guarantees that every change is checked. Also, the last values of other variables in the expression are maintained, so that race conditions are completely avoided in the trigger logic. But inside the function just the current value of the state variables is fetched, which could be after they have changed again.

Would you expect the `x` and `y` attributes to change quickly?

You could add function arguments to capture the variable name and value when the trigger occurred, and log them to compare with the current values.  Or for testing purposes you could add a new function that triggers off any change to `camera.sofie.vacuum_position.x` and log the `value` in the function argument - that will be guaranteed to show every state change event.  That will show whether they change rapidly.

**Comment by craigbarratt** [comment]
One solution for rapidly changing (eg, noisy) state variables would be to move the expression in `@state_active` to `@state_trigger` and add a non-zero setting for `state_hold`.

**Comment by dlashua** [comment]
This logging:

```
@state_trigger('camera.sofie.vacuum_position')
def sofie_log(**data):
    log.info(f"ID={id(data['value'].vacuum_position)} X={data['value'].vacuum_position.x} Y={data['value'].vacuum_position.x}")
```

Shows this:

```
2020-12-10 07:42:57 INFO (MainThread) [custom_components.pyscript.file.test.sofie_log] ID=139895723336656 X=27636 Y=27636
2020-12-10 07:43:02 INFO (MainThread) [custom_components.pyscript.file.test.sofie_log] ID=139895734703680 X=27636 Y=27636
2020-12-10 07:43:07 INFO (MainThread) [custom_components.pyscript.file.test.sofie_log] ID=139896311878032 X=27636 Y=27636
2020-12-10 07:43:12 INFO (MainThread) [custom_components.pyscript.file.test.sofie_log] ID=139895723786544 X=27636 Y=27636
2020-12-10 07:43:17 INFO (MainThread) [custom_components.pyscript.file.test.sofie_log] ID=139895726229728 X=27636 Y=27636
```

So it's a new object every 5 seconds (which is not great way to write an integration, but, that's what it is), but the values in that object have not changed. Since it's a new object, the pyscript code sees it as a change, which is fine. There's no way around that since pyscript can't possibly know how to compare every object type. However, @state_active should be able to compare them. 

Since it's only once every 5 seconds, it's probably not a race condition due to the values have changed before `@state_active` does its work?

**Comment by dlashua** [comment]
Some further testing around the values of "x" and "y" in vacuum_position show that they are... weird. For instance, even when `value.vacuum_position.x` and `old_value.vacuum_position.x` are the same number, the `id()` of those numbers is different.

So, while I still feel that `@state_active` should have gotten a "False" result when the `eval` did just after it, because the values it's comparing are so strange, it's a VERY edge case for sure. Closing this until I have enough information to point at a solution.

**Comment by craigbarratt** [comment]
Agreed - the race condition is ruled out.  Something is definitely broken.  It would be great to get some more clues to figure it out.  Perhaps you'll need to add some debug statements in `trigger.py` to see what variable arguments get passed into the `state_active` evaluation.
