### ISSUE TITLE
kwargs includes entity instead of attribute

### ISSUE THREAD

**Issue by bouthors** [custom-components/pyscript#127]
Hi,

I use the following code:
```python
@state_trigger("input_select.source_denon","media_player.denon_avr_3310.source != input_select.source_denon")
def denon_sync_source(var_name=None, value=None, old_value=None):
    log.info(f"denon_sync_source: from {var_name} source {value}")
```

The script is correctly started when there is a change, but when "media_player.denon_avr_3310.source" changes the var_name sent is media_player.denon_avr_3310 instead.

sample output:
`2020-12-26 18:43:36 INFO (MainThread) [custom_components.pyscript.file.denon.denon_sync_source] denon_sync_source: from media_player.denon_avr_3310 source on`

Is that a normal behavior ?
I am using version 1.1.0

Best regards,
Matthieu

**Comment by craigbarratt** [comment]
Yes, that is normal and expected.  The `var_name` argument is always the `entity_id` even if attributes are used in the expression.  The `value` and `old_value` contain the full state information including attributes, which gives the function the information it needs to see what changed.

**Comment by bouthors** [comment]
I checked kwargs and in my case the `value` and `old_value` are set to `on`, there is nothing about attributes.

**Comment by dlashua** [comment]
@bouthors `value` looks like it's just a string. But it's not. `value.some_attribute` will work as you might expect.

**Comment by craigbarratt** [comment]
`value` and `old_value` are "magic": they evaluate to the string entity value (eg, `on` in your case), but they also contain the attributes too.  So `value.source` is the `source` attribute, and `old_value.source` is the previous `source` attribute.

The same "magic" behavior happens when you assign an entity variable, eg:
```
save = media_player.denon_avr_3310
```
See the [State Variables](https://hacs-pyscript.readthedocs.io/en/latest/reference.html#state-variables) docs.

**Comment by bouthors** [comment]
Thanks, it's working perfectly with value.attribute !
By the way, thanks for Pyscript, it's amazing and so easy to use.
