### ISSUE TITLE
Support other trigger mechanisms

### ISSUE THREAD

**Issue by Beiri22** [custom-components/pyscript#152]
I'd like to move from regular automations to pyscript. Unfortunately, I am using device_trigger and zone_trigger. Will those be implemented soon?

**Comment by dlashua** [comment]
At the moment, I don't believe pyscript supports this type of trigger. I don't think adding these types of triggers would be too difficult, however, writing code to use them would be. These two types of triggers are more recent in Home Assistant. They work best when using the UI based automation editor because they require the use of less-human-readable device IDs and zone IDs instead of the "friendly" names we've given the various entities.

For `device_trigger`s, if you're using ZHA and wanting to trigger based on button presses on a device, I would look at the "zha_event" event. Most of the device_triggers also send events. Go to developer tools -> Events and listen for "zha_event". Then press buttons on your device and see what shows up. 

For `zone_trigger`s, most of the things you could want to do here have a corresponding state in a zone entity which can be used in a similar way. If you can explain what you're trying to do, I can likely point you in the right direction.

**Comment by Beiri22** [comment]
I will have a look. I found out, that the device is using deconz_event. Thanks so far.

**Comment by sagargp** [comment]
What's the best way to trigger on a person entity entering or exiting a zone?

**Comment by dlashua** [comment]
@sagargp you've commented on a closed issue with a new question. You're unlikely to get any help this way. Try opening a new discussion instead.
