### ISSUE TITLE
Question: Why are global variables handled different?

### ISSUE THREAD

**Issue by Beiri22** [custom-components/pyscript#155]
Given the following example:
```python
num=int(0)
string="0"
arr=[0]
dct={"num":0}
anonld=lambda: None
anonld.num=0
class anoncl: pass
anoncl.num=0

@event_trigger("deconz_event", "id=='tradfri_fernbedienung' and event==5002")
@time_trigger("cron(* * * * *)")
def test(**kwargs):
    num+=1
    string=int(string)+1
    arr[0]+=1
    dct["num"]+=1
    anonld.num+=1
    anoncl.num+=1
    log.info(f"Event: {num} {string} {arr[0]} {dct['num']} {anonld.num} {anoncl.num}")
```

Why are num and string resetted, but all the others work as intended?
```
Event: 1 1 1 1 1 1
Event: 1 1 2 2 2 2
Event: 1 1 3 3 3 3
Event: 1 1 4 4 4 4
Event: 1 1 5 5 5 5
Event: 1 1 6 6 6 6
Event: 1 1 7 7 7 7
Event: 1 1 8 8 8 8
Event: 1 1 9 9 9 9

```

**Comment by craigbarratt** [comment]
First, your example exposes a bug in pyscript that I just fixed - thanks!  The first two lines in the function should raise an exception, which now happens with the change I just pushed.  Previously, it didn't give an error, and used the global variable value, added one to it, and set a local variable to that value.  That's why it's stuck at 1 each time since the global variable doesn't get updated.  This code will now correctly raise an exception, since the local variable isn't initialized.

The reason these generate an exception is that in python a function can't modify a global variable without first declaring it using `global`.  It can access (read-only) global variables without needing a declaration.

However, you can modify the contents of a compound global variable (eg, a list, dict or object), so the remaining lines work fine without the `global` declaration.  The reason is that an assignment like `arr[0] += 1` changes the first element of `arr`, but `arr` itself is still unchanged even if its contents have changed (it is still the same list).

I modified your code to make it vanilla python, and added the `global` declaration.  It works the same in python and pyscript.
```python
num=int(0)
string="0"
arr=[0]
dct={"num":0}
anonld=lambda: None
anonld.num=0
class anoncl: pass
anoncl.num=0

def test():
    global num, string
    num+=1
    string=int(string)+1
    arr[0]+=1
    dct["num"]+=1
    anonld.num+=1
    anoncl.num+=1
    print(f"Event: {num} {string} {arr[0]} {dct['num']} {anonld.num} {anoncl.num}")

test()
test()
test()
```

**Comment by Beiri22** [comment]
I'm new to python - so thanks especially for the background information. I will try your modified code.
