### ISSUE TITLE
Question/ How to return data from service called via API

### ISSUE THREAD

**Issue by mxbranson** [custom-components/pyscript#158]
I'm calling a service created in pyscript via the hass API and would like some feedback sent to the calling app. Is this possible?
I tried printing, @pyscript_compile printing and couldn't find anything in the docs except for logging.

Would really appreciate a way. 
Cheers!

**Comment by craigbarratt** [comment]
Service calls return typically return even before the service is executed.  There is no way for the service call to return any data from the service itself.

So you need another way to get data back.  You could have the service set some entity (state variable) that the pyscript code could wait for (eg, with a `@state_trigger` or `task.wait_until`).  One drawback is that all entity values are forced to be strings, so if you want to return more than just a scalar, you would need to encode and decode it (eg, using json).  Here's an example of this approach (both the caller and service are in pyscript):
```python
@service
def test1():
    # implement the service here
    ...
    # then, at the very end, return the result
    pyscript.test1_result = 1

def call_service():
    # initialize the entity used for the return value and call the service
    pyscript.test1_result = 0
    pyscript.test1()

    # wait for the return value to be set, and log the result
    task.wait_until(state_trigger="pyscript.test1_result != '0'")
    log.info(f"result from service = {pyscript.test1_result}")

call_service()
```
Your calling app could implement `call_service` by registering a state trigger and looking to see when `pyscript.test1_result` changes.  But that takes a bit of work, since you'll need to monitor state changed events.  You could also send an event instead of setting an entity.

Is your calling app written as async code?  If so, another much easier approach is to create an async queue, and passing the queue as a service parameter.  Thats used to deliver the result by writing it to the queue.  Then the calling app simply reads the queue to get the result.  The benefit is that you can write any compound data type to the queue (eg, an object, list, dict etc).  Here's how this would be done:
```python
import asyncio

@service
def test1(result_q=None):
    # implement the service here
    ...
    # then, at the very end, return the result by writing to the queue
    result_q.put(1)

def call_service():
    # create a queue and call the service
    result_q = asyncio.Queue(0) 
    pyscript.test1(result_q=result_q)

    # wait for the reply and log it
    result = result_q.get()
    log.info(f"result from service = {result}")

call_service()
```
If your app is written in async, then `call_service()` is easy to implement, although you'll need an `await` before the `result_q.get()` (it's not needed in pyscript).

**Comment by dlashua** [comment]
@craigbarratt outlined several great ways to get returned data as long as you're calling the service from within pyscript.

However, if you're trying to call the service from Home Assistant then I've found the easiest way to be to fire an event.

```
@service
def add_numbers(id=None, x=0, y=0):
  added = x + y
  event.fire('ADD_NUMBER_RESULT', id=id, result=added)
```

Then you can consume this in Home Assistant like:

```
alias: get results
trigger:
  event: ADD_NUMBER_RESULT
action:
  blah blah blah
```

**Comment by mxbranson** [comment]
Thank you both. I'll try them out and report how I went for posterity.
