### ISSUE TITLE
Detected I/O inside the event loop

### ISSUE THREAD

**Issue by dapuzz** [custom-components/pyscript#16]
Hi
What about this warning in the log? It's my fault?
 
`WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for pyscript doing I/O at custom_components/pyscript/eval.py, line 1143: return func(*args, **kwargs)
`
Thank you

**Comment by craigbarratt** [comment]
One way this could happen is if you import packages and call functions in that package that do I/O (eg, json dump/load, or something that writes to stdout or stderr). While it will still work ok, those functions will block until complete, which will slow down the main event loop.

I was thinking about adding a function that allows you to execute those functions as an executor job (another temporary thread) that moves the blocking operations out of the event loop.

What functions are you calling that could be doing I/O?

**Comment by dapuzz** [comment]
Urlopen, BeautifulSoup and status set. 
Is there any instruction I can use to fork to async process?

**Comment by craigbarratt** [comment]
Ok, that explains the warning message.

I need to add a function that you would use to wrap those I/O functions.  In the meantime, it probably will work ok, so long as those calls execute quickly.

**Comment by craigbarratt** [comment]
I pushed a change 5908b4b that adds a new function, `task.executor()`.  You can use that to call functions in packages that do I/O.  `task.executor()` calls the function using `run_in_executor()`, which runs the function in a thread instead of the event loop.

Its arguments are the function to call, and the arguments that should be passed to that function.  So instead of doing something like:
```
import requests

resp = requests.get('https://raw.githubusercontent.com/custom-components/pyscript/master/README.md')
```
you should do this instead:
```
import requests

resp = task.executor(requests.get, 'https://raw.githubusercontent.com/custom-components/pyscript/master/README.md')
```
There is no need to use `task.executor()` when the following code uses `resp.text` or `resp.status_code` since those don't do I/O. 

This is an experimental feature at this point.  Please tell me if it fixes the warning you saw.

**Comment by craigbarratt** [comment]
One more comment before I close this issue.  If you need to do I/O from pyscript, the best solution is to find a package that is native async-based and use that.  For example, instead of `requests` or `urllib.request.urlopen`, consider using [`aiohttp`](https://docs.aiohttp.org/en/stable/) instead.

Looking at the client examples in `aiohttp`, you can fetch a URL with (there's no need to include the `await` keyword; it is optional in pyscript):
```
import aiohttp

async with aiohttp.ClientSession() as session:
    async with session.get('https://raw.githubusercontent.com/custom-components/pyscript/master/README.md') as resp:
        print(resp.status)
        print(resp.text())
```
This is supported in the master code, but not the current release 0.21.  So if you want to use `async with` you'll need to run the master code instead of 0.21.
