### ISSUE TITLE
Unexpected importing issues

### ISSUE THREAD

**Issue by jlo88** [custom-components/pyscript#162]
I'm trying to use my own modules in pyscript but I ran into some unexpected behaviour. I have these two files in the pyscript folder: 

mod.py
```
def get_input_boolean(name): 
    """Gets the state of an input boolean, returns type bool"""
    full_name = f"input_boolean.{name}"
    val = state.get(full_name)
    try:
        if val == "on":
            return True
        else: 
            return False
    except: 
        log.warning(f"{full_name} could not be found")
        return None
```

test.py: 
```
from pyscript.mod import get_input_boolean

@service
def test_get_input_boolean():
    get_input_boolean("vacuum_automated_cleanup_zone_2_completed")
```

This gives me 

```
2021-02-20 10:31:58 ERROR (MainThread) [custom_components.pyscript.file.test.test_get_input_boolean] Exception in <file.test.test_get_input_boolean> line 5:
        get_input_boolean("vacuum_automated_cleanup_zone_2_completed")
                          ^
NameError: name 'state' is not defined
```

It seems like the pyscript state function is not available in the context of mod.py?

I'm on version 1.2.1

**Comment by wsw70** [comment]
When reading https://hacs-pyscript.readthedocs.io/en/latest/reference.html#importing, I see that

> So if you plan to run large chunks of code in pyscript without needing any of the pyscript-specific features, (...) , you might consider putting them in a package and importing it instead.

I never imported my own code in pyscript but this may be a clue?

**Comment by craigbarratt** [comment]
If you want to create a pyscript module that can be imported by other pyscript scripts, you should put it in `pyscript/modules`, so `mod.py` should be in `pyscript/modules/mod.py`.  See the [docs](https://hacs-pyscript.readthedocs.io/en/latest/reference.html#importing).

If `mod.py` is in the top-level directory, it will be autoloaded (which you don't want for a module), and the `import` will treat it as native python code, which is why `state` is undefined.

**Comment by jlo88** [comment]
I see, my bad! I tried it out and then it works. Thanks for the quick replies!
