### ISSUE TITLE
wrong times for sunrise and sunset, when next occurrence is tomorrow

### ISSUE THREAD

**Issue by fleXible** [custom-components/pyscript#18]
When the next sunset or sunrise is not on the same but the following day, the datetime is only adjusted to be on the next day but for the time, todays value is used.

Sample code:
````python
import datetime as dt

@time_trigger("startup", "once(sunrise)", "once(sunset)")
def test_next_sunrise_tomorrow():
    print(dt.datetime.fromisoformat(sun.sun.next_rising).astimezone())
    print(dt.datetime.fromisoformat(sun.sun.next_setting).astimezone())
````
> [custom_components.pyscript.trigger] trigger: got sunrise = 06:30:35 (t = 2020-09-09 06:30:35+02:00)
[custom_components.pyscript.trigger] trigger: got sunrise = 06:30:35 (t = 2020-09-09 06:30:35+02:00)
[custom_components.pyscript.trigger] trigger: got sunset = 19:36:24 (t = 2020-09-09 19:36:24+02:00)[custom_components.pyscript.trigger] trigger: got sunset = 19:36:24 (t = 2020-09-09 19:36:24+02:00)
[custom_components.pyscript.trigger] trigger jupyter_2.test_next_sunrise_tomorrow time_next = 2020-09-10 06:30:35, now = 2020-09-09 23:03:19.136877
[custom_components.pyscript.trigger] trigger jupyter_2.test_next_sunrise_tomorrow waiting for 26835.863123 secs
[custom_components.pyscript.eval] jupyter_0.test_next_sunrise_tomorrow: calling fromisoformat("2020-09-10T04:32:14+00:00", {})
[custom_components.pyscript.eval] jupyter_0.test_next_sunrise_tomorrow: calling astimezone(, {})
[custom_components.pyscript.eval] jupyter_0.test_next_sunrise_tomorrow: calling print(2020-09-10 06:32:14+02:00, {})
[custom_components.pyscript.jupyter_0.test_next_sunrise_tomorrow] 2020-09-10 06:32:14+02:00
[custom_components.pyscript.eval] jupyter_0.test_next_sunrise_tomorrow: calling fromisoformat("2020-09-10T17:34:02+00:00", {})
[custom_components.pyscript.eval] jupyter_0.test_next_sunrise_tomorrow: calling astimezone(, {})
[custom_components.pyscript.eval] jupyter_0.test_next_sunrise_tomorrow: calling print(2020-09-10 19:34:02+02:00, {})
[custom_components.pyscript.jupyter_0.test_next_sunrise_tomorrow] 2020-09-10 19:34:02+02:00

**Comment by craigbarratt** [comment]
Good catch!  And thanks for the fix.

This makes me realize that sunrise/sunset are also broken when you specify a date as well (eg, `"12/1 sunrise"` is today's sunrise on Dec 1st, instead of the Dec 1st sunrise).  I remember when I wrote this code that I didn't see how to include `now` (which has the target date ) in the call to `sun`.  Directly calling `astral.sun.sun` has an option `date`, but I didn't want to directly call `astral` since I didn't know how to get the lat/long from config...  I need to look at this some more.

Reopening until the date issue is fixed.
