### ISSUE TITLE
Cannot evaluate numpy matricies

### ISSUE THREAD

**Issue by simeneide** [custom-components/pyscript#264]
Not sure when this happened, but numpy as a very weird behaviour when comparing with one number.
For example, running this 

```
@time_trigger()
@state_trigger(["sensor.netatmo_netatmo_lv71_livingroom_co2", "input_number.fan_booster"])
def ventilation(**kwargs):
    import numpy as np
    np.zeros((5,5))>0
```

results in 

```
2021-11-14 18:44:17 ERROR (MainThread) [custom_components.pyscript.file.ventilation.ventilation] Exception in <file.ventilation.ventilation> line 56:
        np.zeros((5,5))>0
                        ^
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

The expected behaviour is to get a 5x5 numpy boolean tensor where each index has been evaluated to bigger than zero or not.

This was working before, has anything changed?

**Comment by dlashua** [comment]
Usage of Native Python modules, especially those that return non-native data types, causes issues due to the nature of how pyscript works. You need to decorate these functions in `@pyscript_compile`. Note: within such a decorated function, pyscript functionality (i.e. `log.info`, `state.get`, or directly accessing entity ids) doesn't work. It's one or the other. The above can be rewritten like this:

```python
@time_trigger('startup')
def ventilation(**kwargs):
    specialthing()

@pyscript_compile
def specialthing():
    np.zeros((5,5))>0
```

**Comment by simeneide** [comment]
great that worked, thanks for clarifying :)
