### ISSUE TITLE
Feature Request: access entity attributes as object attributes

### ISSUE THREAD

**Issue by dlashua** [custom-components/pyscript#27]
I have pyscript app YAML like this:

```yaml
- app: calc_setpoint
  sensor_temp: climate.downstairs
  sensor_temp_attr: current_temperature
```
Notice, sensor_temp_attr, which is optional as consumed by this code:

```python
    sensor_temp_sensor = data.get('sensor_temp')
    if sensor_temp_sensor is None:
        log.error(f'{climate_entity}: sensor_temp is required')
        return

    sensor_temp_attr = data.get('sensor_temp_attr')
    if sensor_temp_attr is None:
            sensor_temp = float(state.get(sensor_temp_sensor))
    else:
            sensor_temp = float(state.get_attr(sensor_temp_sensor)[sensor_temp_attr])
```
If entity attributes were accessible as object attributes my code would be simpler:

```yaml
- app: calc_setpoint
  sensor_temp: climate.downstairs.current_temperature
```

```python
    sensor_temp_sensor = data.get('sensor_temp')
    if sensor_temp_sensor is None:
        log.error(f'{climate_entity}: sensor_temp is required')
        return

   sensor_temp = float(state.get(sensor_temp_sensor))
```

For other uses, it would also make state_trigger expressions easier:

```python
@state_trigger('climate.downstairs.current_temperature > 75')
```

vs (and I don't even know if this code works):
```python
@state_trigger('state.get_attr('climate.downstairs')['current_temperature'] > 75')
```

If there is a namespace collision issue at the root of the state variable, this syntax would be second best:
```
climate.downstairs.attributes.current_temperature
```

**Comment by dlashua** [comment]
I went to see if this was something I could add myself, only to see it's already there. So it's just not documented. Excellent!

**Comment by craigbarratt** [comment]
As you discovered, `state.get(name)` can directly get an attribute if `name` is of the form `domain.entity.attr`.  I need to update the docs.

Similarly, you can put attributes of the form `domain.entity.attr` into `@state_trigger` expressions.  Every time the state variable `domain.entity` changes the expression will be evaluated.  I also need to mention that in the docs.

Unfortunately, dynamically evaluating the state variable or attribute with `state.get()` or `eval()` in a `@state_trigger` expression doesn't work, since pyscript can't figure out ahead of time what variable to watch to trigger the expression.  It is looking for identifiers (plain variable names) in the expression. So while this works
```
@state_trigger('climate.downstairs.current_temperature > 75')
```
this form does not work:
```
@state_trigger('state.get("climate.downstairs.current_temperature") > 75')
```
Perhaps I could add an optional keyword argument where you can explicitly say which variables to watch, which would be helpful when the state trigger is based on an expression rather than identifiers, eg:
```
@state_trigger("compute_something() > 10", watch_vars={"climate.downstairs"})
```
(although that would be better written as `@state_trigger("compute_something(climate.downstairs) > 10")`)

This would make the somewhat confusing:
```
@state_trigger("True or climate.downstairs")
```
equivalent to and more clearly expressed as:
```
@state_trigger("True", watch_vars=["climate.downstairs"])
```
Re-opening until I update the docs and decide whether to add a `watch_vars` keyword.

**Comment by craigbarratt** [comment]
Added to docs with 5a10c2c.  Closing now; `watch_vars` kwarg is still on the consideration list.  Not sure if it's really needed.
