### ISSUE TITLE
"old" doesn't work in state_trigger

### ISSUE THREAD

**Issue by dlashua** [custom-components/pyscript#29]
pyscript:
```python
@state_trigger("input_boolean.test_1 == 'on' and input_boolean.test_1.old == 'off'")
def report_old():
    log.info('report with old ON')
```

Triggering this results int the following error:
```
2020-10-05 05:59:40 ERROR (MainThread) [custom_components.pyscript.file.test.report_old] Exception in <file.test.report_old @state_trigger()> line 1:
    input_boolean.test_1 == 'on' and input_boolean.test_1.old == 'off'
                                     ^
AttributeError: 'str' object has no attribute 'old'
```

**Comment by craigbarratt** [comment]
I think this got broken when I changed state variables to throw an exception when undefined (previously silently returned `None`).  I pushed a change  4896090 so that inside `@state_trigger` undefined state variables, attributes and `.old` default to `None`, since you can't use a `try/except` inside an expression.

Note that when using `.old`, the very first time a state variable is set, `.old` will be `None`, so you might want to do this:
```python
@state_trigger("input_boolean.test_1 == 'on' and (input_boolean.test_1.old == 'off' or input_boolean.test_1.old is None)")
```
Also, if the expression refers to multiple state variables with `.old`, only the one that just changed will have `.old` set; the others will be `None`.

**Comment by dlashua** [comment]
Excellent! I'll let you know when I get a chance to test this. And Thank You!

**Comment by dlashua** [comment]
This is working as expected. Thanks, again!
