### ISSUE TITLE
state.persist is broken in HA 2022.3

### ISSUE THREAD

**Issue by LeszekSwirski** [custom-components/pyscript#331]
https://github.com/home-assistant/core/pull/66068 changed the signature of `async_restore_entity_added` from taking an entity `str` to taking a `RestoreEntity`

**Comment by dlashua** [comment]
It looks like we'll need an "Entity" that extends "RestoreEntity". But we aren't actually using "Entity" at the moment.

I believe this will require us to treat all entities similar to how they were handled in [PR #129](https://github.com/custom-components/pyscript/pull/129)

**Comment by jrowberg** [comment]
Confirm that I am unable to create persistent state vars with the latest versions of everything installed. This is my first day playing with PyScript and I'm glad to see it's not just me!

**Comment by dlashua** [comment]
I haven't tested this with any of my actual pyscripts because I'm not quite ready for a 2022.3 upgrade yet. But if any brave souls want to try PR #332 and let me know if it works for you that'd be great.

**Comment by jrowberg** [comment]
Thanks, @dlashua! I just pulled the modified file into my `custom_components` location, restarted HASS, and boom! The problem is gone, and persisting states appears to work.

**Comment by dlashua** [comment]
@jrowberg glad to hear it. Hopefully, this weekend I'll have some time to fix this properly if @craigbarratt doesn't beat me to it.

**Comment by selmaohneh** [comment]
Another thanks to @dlashua! I tried the temporary fix, as well. Seems to work :-)

* Most of my pyscript services were missing after the update --> they are now back
* All persisted states were missing after the update --> they are now back

Note: My persisted states all were on "unknown" after the HASS restart. This is my default value from `state.persist`. That's why I triggered some state changes manually to get the states up to date again. But I guess I could have just waited some longer for the actual state changes.^^
