### ISSUE TITLE
event_trigger does not work inside closures

### ISSUE THREAD

**Issue by assumptionsoup** [custom-components/pyscript#434]
```
def register_pico_light(pico_id, lights):

    @event_trigger('lutron_caseta_button_event')
    def pico_button_test(**kwargs):
        log.error(f"got EVENT_CALL_SERVICE with {kwargs}")

register_pico_light('<my_device_id>', ['light.desk'])
```
This doesn't work, but placing `pico_button_test` outside of the register function does. It would be nice if this was possible.

**Comment by craigbarratt** [comment]
The issue is that when `register_pico_light` returns (which is immediately), `pico_button_test` is no longer referenced and is destroyed.  You need to save a reference to the function.

See the documentation for [trigger closures](https://hacs-pyscript.readthedocs.io/en/latest/reference.html#trigger-closures).
