### ISSUE TITLE
Ordering various Pyscript script is unpredictable at cold boot

### ISSUE THREAD

**Issue by dominig** [custom-components/pyscript#452]
I need to read a state variable maintain by a Pyscript from another pyscript.
It works fine as long as I do not any cold boot.
I have tried to make an active wait by trying to watch the variable creation with:
 `state.names(domain=pyscript) `
before creating the triggers but it blocks the boot process on pyscript initialisation.
A task.sleep(30) does not help either as it seems that initialisation of scripts is sequencial until a trigger call is reached.
How to overcome the issue of requiring the existence of a state variable before proceeding ?
A simple garanted startup order would do. Alphabetic, priority, ...

**Comment by craigbarratt** [comment]
As you discovered, the load order isn't guaranteed, and each file is loaded sequentially so you can't introduce delays at the top level.

Inside HASS & HACS, the load order of integrations isn't guaranteed either.  So that's why pyscript doesn't arm any triggers until the `EVENT_HOMEASSISTANT_STARTED` event occurs.

There are various solutions you could consider.  For example, the script that sets the state variable can do so at load time (ie, not inside a function).  The script that watches it can do so via a `@state_trigger` and/or `@time_trigger("startup")`.

**Comment by dominig** [comment]
Could be a good idea to make it clear in the documentation. 
Thanks Dominig 

Le 27 mars 2023 01:19:09 GMT+02:00, Craig Barratt ***@***.***> a écrit :
