### ISSUE TITLE
Feature Request: Declare new restorable state from pyscript

### ISSUE THREAD

**Issue by swazrgb** [custom-components/pyscript#47]
It is currently possible to declare new state from pyscript very easily like `some_domain.abc = 'def'`, even if `some_domain` or `some_domain.abc` does not yet exist.

This is very helpful for scripts that want to define their own state. However these states are not automatically persisted when home assistant restarts. A workaround is for the user to manually precreate a `input_text.abc` helper then manipulating that from pyscript.

However this is rather inconvenient because for every state variable the user has to perform some manual tasks.

So it would be nice if it was somehow possible to define restorable states from pyscript.

**Comment by dlashua** [comment]
Not the Author of pyscript, just a fan... but...

I want this too. Unfortunately, it's quite hard to do it "right". 

For `binary_sensor` and `sensor`, it's not incredibly hard, since they only set values, and never receive service calls. However, for each domain, pyscript would have to do some setup tasks. And unless pyscript just provided the actual Home Assistant Entity Object to your script to manipulate, it'd also have to provide some convenience functions for setting values. 

For `switch`, `light`, `climate` and such, the same is true as above, except these also receive service calls. Which means you'd either have to listen for all the appropriate events, or pyscript would have to provide more convenience functions for this.

For non-standard domains (like your example `some_domain`) they'd have to be catered to similarly to `binary_sensor`, but in a different way.

Directly setting the state (`state.set('binary_sensor.test', 'on')`) gets the job done, but it's rogue in Home Assistant ecosystem. If there's already an entity with that entity_id, it's overwritten. You can't rename the entity in the UI. The state isn't restored on restart.

I wrote a proof-of-concept custom_component to allow setting and restoring arbitrary states in Home Assistant. It has the same caveats as `state.set()`, with the exception that it DOES restore state. But if you overwrite an existing entity_id, not only will it overwrite it, it'll restore that overwrite on Home Assistant restart.

You're welcome to check it out: [hass-setter](https://github.com/dlashua/hass-setter)

I don't actually use this, though it does the bare minimum of what you're asking for. Once installed, in pyscript you could use it like this:

```
setter.set(entity_id='binary_sensor.test', state='on', attributes={'friendly_name':'Test'})
```

Perhaps @craigbarratt can find a better way around these limitations, presuming this feature is considered "in-scope" for pyscript.

**Comment by swazrgb** [comment]
Perhaps limiting this request to the `pyscript` domain would make more sense. My goal is for pyscript scripts to be able to store (and persist) state for internal use.

It is currently also possible to do `pyscript.some_state = 'abc'`, so if it would be possible to persist such values that would be great. I now understand that expanding this capability to arbitrary domains is likely undesirable.

**Comment by dlashua** [comment]
See commented on PR #48 .
