### ISSUE TITLE
Feature Request: Service Closure

### ISSUE THREAD

**Issue by rajeee** [custom-components/pyscript#509]
The ability to use closure for Triggers and being able to define a range of trigger functions in a loop is very handy. Could you also extend this functionality to @service definitions? Looks like its not possible to create multiple services with

```
all_services = []
for i in range(10):
	@service(f"test.service{i}')
	def func():
	    log.debug(f"Service {i}")
    all_services.append(func)
```

All of the test.servicex will print the last service, service 9.

**Comment by craigbarratt** [comment]
It should work with `@service` too, although I don't think I tested that.

The problem with your code is that the variable `i` inside every `func()` is bound to the same single variable `i`, which has the value 9 after the loop.  It's not evaluated until the function is called.  So when the service is called, the f-string is evaluated and `i` has the value 9.  The `@service` is evaluated when the function is defined, so that will work as you expect.

**Comment by rajeee** [comment]
Ha! Thanks. I forgot how closure is supposed to work in python! I can confirm that the suggest fix works.
Maybe worth adding a note in the documentation that this works with services (and other things?) too.
