### ISSUE TITLE
Possible to access the old state attributes?

### ISSUE THREAD

**Issue by Nxt3** [custom-components/pyscript#52]
I have a state trigger for something I wanted to do that should look like this but doesn't work:

```
homeTheaterTvId = "media_player.tv"

@state_trigger(f'{homeTheaterTvId}.old.source != "HDMI-5"')
def doSomething():
   ...
```

I know this doesn't work since `.old: str`, but how would I do something like this? Is it possible to access the old state attributes?

unrelated: pyscript is fantastic and has helped me get into the automation game with such ease!

**Comment by craigbarratt** [comment]
I don't think HASS maintains old state variable attributes (it only provides the `old` value in a state change event, which is why it's only available in triggers), and it wouldn't make sense for pyscript to shadow all states to keep the old attributes.

One solution is triggering the function anytime the source changes, and putting the check on the old attribute value inside `doSomething()`:
```
homeTheaterTvId = "media_player.tv"
tv_id2source = {
    homeTheaterTvId: state.get_attr(homeTheaterTvId)["source"],
}

@state_trigger(f'{homeTheaterTvId}.source != tv_id2source["{homeTheaterTvId}"]')
def doSomething():
    if tv_id2source[homeTheaterTvId] != "HDMI-5":
         ...
    # at the end of the function, update the current source
    tv_id2_source[homeTheaterTvId] = state.get_attr(homeTheaterTvId)["source"]
```
This would look simpler if `homeTheaterTvId` was fixed (you could replace the `state.get_attr()` calls with just `media_player.tv.source` , but the way you've written it allows it to be extended to multiple media devices easily.  Also, it is untested...

**Comment by Nxt3** [comment]
Ah shoot I'm sorry; I'm pretty new to Home Assistant and didn't realize it didn't store the previous state's attributes too. My bad. Definitely fair for pyscript to not have to handle that 😉 

What do you mean when you say "This would look simpler if `homeTheaterTvId` was fixed..."? I had been setting a global variable to hold the entity_id for the entity I wanted (in my case, my TV is `media_player.tv`). Isn't that fixed?

**Comment by craigbarratt** [comment]
I'm pretty new to HA too.

Here's what I meant: if you just have one device you could write it this way:
```
tv_source = media_player.tv.source

@state_trigger("media_player.tv.source != tv_source")
def doSomething():
    global tv_source
    if tv_source != "HDMI-5":
         ...
    # at the end of the function, update the current source
    tv_source = media_player.tv.source
```
which is a lot easier to read and understand (once again, this is untested).

**Comment by Nxt3** [comment]
This works for me! Thanks for pointing me in the right direction--definitely making it easy to love pyscript.
