### ISSUE TITLE
Issues using yaml module in pyscript

### ISSUE THREAD

**Issue by erkr** [custom-components/pyscript#593]
I'm using the yaml module to parse ha yaml files. 
Not sure if this is a pyscript issue, a pyyaml issue, or the combination. But I'm stuck.

The issue:
HA yaml files contain unsupported tags like `!include` and `!secret`. So I added constructors to handle them and ran into the issue that an await is missing somewhere.

I made the most simple example  possible to demonstrate the issue.

The code:
```python
class YamlLoader(yaml.SafeLoader):
    pass

def test_constructor(loader: yaml.SafeLoader, node: yaml.nodes.ScalarNode) -> str:
   return f"!Test handled"

YamlLoader.add_constructor('!Test', test_constructor)


yaml_str = """\
example: !Test foo
"""

@service(supports_response="only")
def test():
    data = yaml.load(yaml_str, Loader=YamlLoader)
    return {"data":str(data)}
``` 

When I run this test script in the Dev Tools, the response is this:

``` 
data: "{'example': <coroutine object EvalFuncVar.__call__ at 0x7f419cf4c0>}"
``` 
I expected "!Test handled" in stead of the "<coroutine..."

In the HA log this warning is logged:
``` 
This error originated from a custom integration.

Logger: py.warnings
Source: custom_components/pyscript/eval.py:491
Integration: Pyscript Python scripting (documentation, issues)
First occurred: 20:18:43 (1 occurrences)
Last logged: 20:18:43

/config/custom_components/pyscript/eval.py:491: RuntimeWarning: coroutine 'EvalFuncVar.__call__' was never awaited retval = await func.call(ast_ctx, **data)
``` 

It works fine when executing the code directly in a Python interpreter. 
I then remove `@service...` and adds line to call test()

Best Eric

**Comment by craigbarratt** [comment]
The issue is that all functions and classes in `pyscript` are async.  `yaml.load` is expecting `Loader` to be a regular callback function, not an async function (see the 3rd bullet in the [docs](https://hacs-pyscript.readthedocs.io/en/latest/reference.html#language-limitations)).

Here are three potential solutions:
- use an async-aware library, which I don't think is possible in this case
- move your class into a package so it is native python (see the [docs](https://hacs-pyscript.readthedocs.io/en/latest/reference.html#importing))
- add a `@pyscript_compile` before the class declaration (see the [docs](https://hacs-pyscript.readthedocs.io/en/latest/reference.html#pyscript-compile))

**Comment by erkr** [comment]
@craigbarratt 
Thanks for helping out. I needed to combine options 2 and 3 and note it works 🥳

I created this module:
```python 
import yaml

@pyscript_compile
class YamlLoader(yaml.SafeLoader):
    pass

@pyscript_compile
def test_constructor(loader: yaml.SafeLoader, node: yaml.nodes.ScalarNode) -> str:
   return f"!Test handled"
   
def yaml_loader():
   loader = YamlLoader
   loader.add_constructor('!Test', test_constructor)
   return loader
```  
And this service script:
```python 
import yaml
from yaml_loader import yaml_loader


yaml_str = """\
example: !Test foo
"""

@service(supports_response="only")
def test():
    data = yaml.load(yaml_str, Loader=yaml_loader())
    return {"data":str(data)}
``` 

And that indeed works:
`data: "{'example': '!Test handled'}`

Thank, Eric
