### ISSUE TITLE
Inconsistent `map` behavior when compared with standard python interpreter: expected str instance, coroutine found

### ISSUE THREAD

**Issue by jsamr** [custom-components/pyscript#633]
Running this code [with Python interpreter](https://www.programiz.com/online-compiler/3uyzKlBYLHJbW)...
```python
def entity_is_on_expr(entity):
    return f"{entity} == 'on'"

presence_sensors_entities = ['one', 'two']
presence_expressions = ' or '.join(map(entity_is_on_expr, presence_sensors_entities))

print(f"Join expression: {presence_expressions}")
```
...  shows the following in the console:
```
Join expression: one == 'on' or two == 'on'
```

Which is what I would expect in pyscript. Unfortunately, I get a type error instead:

```
2024-09-08 09:12:58.014 ERROR (MainThread) [custom_components.pyscript.apps.autolight.startup] Exception in <apps.autolight.startup> line 39:
presence_expressions = ' or '.join(map(entity_is_on_expr, presence_sensors_entities))
^
TypeError: sequence item 0: expected str instance, coroutine found
```

Pyscript version 1.6.1

**Comment by craigbarratt** [comment]
Yes, `map` doesn't work correctly in `pyscript` because all functions in `pyscript` are async (coroutines), and `map` expects a regular function.

You should add a `@pyscript_compile` before the definition of `entity_is_on_expr()`, which should make it a regular function.  See the [docs](https://hacs-pyscript.readthedocs.io/en/latest/reference.html#pyscript-compile).

**Comment by jsamr** [comment]
Just realized this after reading the section you mentionned above; `@pyscript_compile` did work; thanks!
