### ISSUE TITLE
Component error: pyscript - No module named 'packaging'

### ISSUE THREAD

**Issue by dapuzz** [custom-components/pyscript#90]
Hi
Can you help me fixind this issue? 
I have upgraded via HACS from 0,xx to 1.0.0 but now I am stuck with this log.

Running HA in virtual env python_version 3.7.3

Thanks

**Comment by dapuzz** [comment]
I reverted back to 0,32 and everything is working fine.

**Comment by dlashua** [comment]
@raman325 I believe this is related to your requirements PR. 

The "packaging" module seems to be already installed for me, so I don't have this issue. I run the latest version of HA in docker. However, it's not specified in pyscript's `manifest.json` so it won't be installed if it isn't already. Should it be added there?

**Comment by raman325** [comment]
hmm @dapuzz what version of Home Assistant are you running? Home Assistant uses the `packaging` module internally but I can't find any references to installing it within the HA code so I assumed it was expected to always be there. I can build a fix for this, I just want to make sure that it is needed before getting too far into it.

**Comment by raman325** [comment]
I stand corrected, latest can work on Python 3.7

**Comment by raman325** [comment]
OK I stand corrected again, HA development uses `packaging` but the actual application does not. Will submit a fix soon.

**Comment by dapuzz** [comment]
I reported using 0.115 but now I am running ha 0.117.  
The point is that “packaging” is a prerequisite when using pip, so I think pyscript is not using my venv for some reason, but some other python installation on my rpi

**Comment by raman325** [comment]
`pyscript` uses HA's installation function for installing packages, so it would be installing packages using the same pip that HA is. I don't think `pip` needs `packaging` because I just created a new virtual environment and it wasn't there. Regardless, can you try cloning the following repo and moving the `custom_components/pyscript` folder into your HA custom_components folder? I can't write a test for this so just want to see if it resolves your issue (it installs `packaging` on demand)

https://github.com/raman325/pyscript/tree/install_packaging

**Comment by dapuzz** [comment]
I confirm this solution works. I was able to grab the installation process and everything has gone ok.
``
/srv/homeassistant/bin/python3 -m pip install --quiet packaging --upgrade --constraint /srv/homeassistant/lib/python3.7/site-packages/homeassistant/package_constraints.txt``

Thanks again, you can merge and close this issue
Bye

**Comment by raman325** [comment]
Thanks for confirming @dapuzz
