### ISSUE TITLE
Question: how to listen for any state changes of a given entity?

### ISSUE THREAD

**Issue by wsw70** [custom-components/pyscript#94]
I am going through the Jupyter examples and documentation and see examples that show how to listen for a **specific** state of an entity:

```python
@state_trigger("pyscript.state_trig_run == '1'")
def state_trig_func(**kwargs):
    log.info(f"state_trig_func called with kwargs={kwargs}")
```

How to listen for any state change of `pyscript.state_trig_run`? Should I listen to the event [`state_changed`](https://www.home-assistant.io/docs/configuration/events/#event-state_changed)? (I would find it more "natural" to listen for state changes in a decorator called `@state_trigger`)

I tried

```python
@state_trigger("pyscript.state_trig_run")
def state_trig_func(**kwargs):
    log.info(f"state_trig_func called with kwargs={kwargs}")
```
but this does not fire when `pyscript.state_trig_run` changes

**Comment by wsw70** [comment]
There seems to be an issue with my Jupyter notebook. When manually changing the state in HA the function was triggred. Sorry for the trouble.

(I also do not see the output of `log.*` in the notebook, so there is something wrong anyway there.)

**Comment by dlashua** [comment]
Are you using the Jupyter Notebook web interface or are you using it through VSCode? Through VSCode, logging like this doesn't display in the notebook as you would expect. Beyond that, yes, the way you are listening for state changes is the recommended way to do so in pyscript. The only reason to use the "state_changed" event directly would be if you wanted EVERY published state change, even if the state didn't actually change (since pyscript's @state_trigger filters the non-changes out for you).
