### ISSUE TITLE
Feature Discussion: autoload pyscript files in sub-directories

### ISSUE THREAD

**Issue by craigbarratt** [custom-components/pyscript#97]
There have been multiple requests on the forum to support loading of script files in subdirectories (other the special directories `apps` and `modules`). That helps users organize their script files, rather everything being in flat top-level directory.

I'm summarizing [my reply](https://community.home-assistant.io/t/pyscript-new-integration-for-easy-and-powerful-python-scripting/215967/75?u=craigb) to one of these requests to get feedback before implementing it.

Questions:
* should pyscript automatically load scripts recursively in all other directories?
* ...or should we reserve a name like `local`, and everything below just that directory is recursively auto loaded?
* should the directories that are recursively autoloaded be configurable?

My leaning would be to have one directory, eg, `local`, which has recursively autoloading, and not make its name configurable. My reasoning is that we might add other top-level directories that support special behavior, so keeping the recursive loading to one directory for now would avoid future name collisions. For config, I prefer to keep things as simple as possible, but we could always make it configurable later (eg, a list of directories to recursively autoload, and the default is `local`).

Another feature could be that script file names starting with `#` are not autoloaded. So you can rename files to disable them (sort of like a comment in the file name). That's easier than moving them to some other directory (and then forgetting where you put it), or commenting out the entire contents of the file. Is that useful or too confusing?

**Comment by dlashua** [comment]
I like the idea of recursive autoloading. I do this now, to some extent [like this](https://gist.github.com/dlashua/f7d88f9a5afdcf7af17ce24266925a0b) but it doesn't work perfectly: New files don't get autoloaded, Deleted files don't get unloaded, and if I make a mistake bad enough that the parser can't get through the file on reload without an exception, then it doesn't load and reload doesn't work then either.

Using "#" at the beginning of a file name (and directory?) is a really clever idea. In other frameworks where I want to not-autoload something temporarily, I have to move it to another directory and, like you said, it's annoying. I especially like it if adding the "#" will cause the existing script to UNLOAD and taking the "#" off will cause it load back up near-immediately.

If the top level 'pyscript/' directory is autoloaded, there's no need to configure it at all. Having only one subdirectory that gets autoloaded works fine too, and, since it's recursive, I don't see any reason to make it configurable. However, I'm not sold on the name 'local'. What about 'autoload', instead, since it's the only directory that will have such treatment? Regardless of what it is named, it would be a one time change to move everything into that directory to get these features, so, not a big deal.

**Comment by craigbarratt** [comment]
Thanks for the comments.  To summarize:
* `scripts` is a good suggestion - let's go with that
* `#`will work on files and subdirectories
* "commenting" a file or directory will cause it to be unloaded on the next reload
When I implement #74 then on linux hosts the unloading/reloading will be immediate whenever a script file is created/modified/renamed (no need for the `reload` service call).

**Comment by dlashua** [comment]
This sounds great!
